### ISSUE TITLE
Option: confirm upgrade

### ISSUE THREAD

**Issue by vh** [josmo/drone-rancher#1]
Confirm upgrade when it is done (like rancher-compose --confirm-upgrade). That will be useful for staging environment. Now with the second push error "Unable to upgrade service" appears.

**Comment by johnrengelman** [comment]
+1

**Comment by johnrengelman** [comment]
I think this should do it: https://github.com/drone-plugins/drone-rancher/pull/3

**Comment by nlf** [comment]
Closed via #3
