### ISSUE TITLE
Batch size and batch interval

### ISSUE THREAD

**Issue by ColtonProvias** [josmo/drone-rancher#13]
It would be great to be able to alter the batch size at least.  If you have a global container across 10 separate hosts with the image being 250 MB in size, it can take a while to upgrade them 1 at a time.  Allowing for adjustable batch sizes would allow for more to upgrade simultaneously, thus speeding up deployment.

**Comment by cusspvz** [comment]
I find this completely useful to be implemented!

Found this can be done with current [go-rancher's client](https://github.com/rancher/go-rancher/blob/121abb93e27120a438c626bc580ddc987577f1e4/client/generated_in_service_upgrade_strategy.go#L10), unfortunately I am not a Go developer. :/

**Comment by ColtonProvias** [comment]
Looking into it now, it looks like it's just 4 lines that have to be added.  After Line 21 in main.go, adding:

``` go
    BatchSize    int64   `json:"batch_size,omitempty"`
    IntervalMillis    int64    `json:"interval_millis,omitempty"`
```

And then after line 116:

``` go
        BatchSize:             vargs.BatchSize,
        IntervalMillis:             vargs.IntervalMillis,
```

Then it's just updating the documentation appropriately.

**Comment by josmo** [comment]
The latest version of the plugin for drone .5 now has this :)
