### ISSUE TITLE
Rancher Load Balancer Support

### ISSUE THREAD

**Issue by JustinPullen** [josmo/drone-rancher#18]
It would be awesome to wrap support for Rancher's LB into this plugin.  

The idea would be to focus rancher LBs and remove targets from the LB. Then preform an image upgrade and add the target back to the LB after the upgrade has been confirmed. This could solve true zero downtime/rolling deployments in rancher, from the CI server, for production setups.

**Comment by josmo** [comment]
@JustinPullen Can you describe a bit more what you're thinking on this?  I thought that if you do rolling service updates behind a lb it would have zero downtime, but maybe I'm missing something.

**Comment by josmo** [comment]
I'm going to close this out since it's been a while.  If it's something needed feel free to reopen :)
