### ISSUE TITLE
Ability to change sidekicks images when upgrading a service

### ISSUE THREAD

**Issue by berisberis** [josmo/drone-rancher#22]
SecondaryLaunchConfig is used in the Rancher Api for this, but i don't know more details.

**Comment by berisberis** [comment]
Something similar as this from gitlabCi-rancher plugin:

https://github.com/cdrx/rancher-gitlab-deploy/commit/5bf7f74338c071ec39b4a0ff0f65bd5a119dd822?diff=split

**Comment by josmo** [comment]
Sounds reasonable :)  When I get a chance I'll look at it, otherwise if you want to submit a PR I'll definitely merge it in.

**Comment by rakhmanov** [comment]
Pull request is up: #33

**Comment by josmo** [comment]
merged in. Should be in latest soon and 1.0.1
