### ISSUE TITLE
Error using Rancher v1

### ISSUE THREAD

**Issue by meskis** [josmo/drone-rancher#28]
Getting an error:

`
time="2017-11-05T14:09:18Z" level=info msg="Drone Rancher Plugin built" 
0s
2
2017/11/05 14:09:20 Unable to upgrade service FE-APP-PROD/react-client: Action [upgrade] not available on [&{1s42 service map[environment:http://beta.dev.co:9999/v1/environment/1e23 self:http://beta.dev.co:9999/v1/services/1s42 consumedbyservices:http://beta.dev.co:9999/v1/services/1s42/consumedbyservices networkDrivers:http://beta.dev.co:9999/v1/services/1s42/networkdrivers serviceLogs:http://beta.dev.co:9999/v1/services/1s42/servicelogs storageDrivers:http://beta.dev.co:9999/v1/services/1s42/storagedrivers containerStats:http://beta.dev.co:9999/v1/services/1s42/containerstats account:http://beta.dev.co:9999/v1/services/1s42/account configItemStatuses:http://beta.dev.co:9999/v1/services/1s42/configitemstatuses consumedservices:http://beta.dev.co:9999/v1/services/1s42/consumedservices instances:http://beta.dev.co:9999/v1/services/1s42/instances serviceExposeMaps:http://beta.dev.co:9999/v1/services/1s42/serviceexposemaps] map[rollback:http://beta.dev.co:9999/v1/services/1s42/?action=rollback remove:http://beta.dev.co:9999/v1/services/1s42/?action=remove finishupgrade:http://beta.dev.co:9999/v1/services/1s42/?action=finishupgrade removeservicelink:http://beta.dev.co:9999/v1/services/1s42/?action=removeservicelink addservicelink:http://beta.dev.co:9999/v1/services/1s42/?action=addservicelink setservicelinks:http://beta.dev.co:9999/v1/services/1s42/?action=setservicelinks]}]
`

Could it be, that Rancher API was changed?

**Comment by josmo** [comment]
That usually happens if a previous upgrade wasn't finished and the upgrade on the service can't take place.  What version of Rancher are you on?

**Comment by meskis** [comment]
Looks like sorted out. Thanks!
