### ISSUE TITLE
How to clear a specific rancher environment?

### ISSUE THREAD

**Issue by sirius1024** [josmo/drone-rancher#30]
I have many environment in rancher, How to assign a specific one to drone-rancher to update stack/service?

**Comment by 0rax** [comment]
Hey, I do not know if there is a specific way of doing so with a multi-environment API Key though I would suggest to use an environment specific key for the plugin, which can be created in `API > Keys` section under `Advanced options`.

The key generated here will only have access to the specific environment it has been created in and will allow you to do what you want.

**Comment by sirius1024** [comment]
Thanks for your help! It worked with your idea.

**Comment by josmo** [comment]
@sirius1024 since it sounds like you have a solution I'm going to close it out. Feel free to re-open if it's still an issue :)
