### ISSUE TITLE
Problem with secrets

### ISSUE THREAD

**Issue by mckernanin** [josmo/drone-rancher#31]
I started a thread on the drone discourse, posting here as well. I think I'm following the docs on this repo but it's not working. 

https://discourse.drone.io/t/problem-with-rancher-plugin-secrets/1739

====================================================

I can't figure out how to configure the rancher plugin properly. Here's my .drone.yml:
https://github.com/tahosalodge/elections-frontend/blob/master/.drone.yml

And for that repo, here's a screenshot of the defined secrets:
<img width="693" alt="screenshot 2018-02-09 13 12 46" src="https://user-images.githubusercontent.com/6300047/36048399-5b0b1bd6-0d9c-11e8-877b-5399790438b4.png">

On my latest build I get this:
```
    time="2018-02-09T19:49:16Z" level=info msg="Drone Rancher Plugin built" 
    time="2018-02-09T19:49:16Z" level=fatal msg="Eek: Must have url, key, secret, and service definied"
```

**Comment by josmo** [comment]
I just answered on discourse, looks like you are trying to use access_secret instead of secret_key which is causing you your problems

**Comment by mckernanin** [comment]
Ugh, thank you.
