### ISSUE TITLE
Force pull

### ISSUE THREAD

**Issue by qrpike** [josmo/drone-rancher#9]
Add the ability to make the upgrade force pull images. Helpful when using :latest tags.

**Comment by ndelitski** [comment]
+1

**Comment by andrewmclagan** [comment]
- 1

**Comment by steve-gray** [comment]
This is a _rancher_ side option. When you set 'always pull' on an image, this is basically what you get each time an instance is recycled or upgraded.

**Comment by josmo** [comment]
I'm closing this issue since you can set 'always pull' on the service side.  If someone wants this reopened just let me know.

**Comment by codecraftm** [comment]
@josmo how can I use drone-rancher with Force pull

**Comment by josmo** [comment]
@minlingchao1 It's a setting on the rancher service where you can have it always pull. I think it's default when you create the service.
